# Generated by Django 4.1.1 on 2022-10-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trip_actual_position_alter_trip_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
