# Generated by Django 4.1.1 on 2022-09-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_container_driver_merchandise_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
