# Generated by Django 4.1.1 on 2022-09-24 01:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_client_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panne',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='actual_position',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vidange',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='container',
            name='container_capacity_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='mileage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='volume_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='weight_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='panne',
            name='mileage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='client_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='consumption',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_capacity_quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicule_mileage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vidange',
            name='mileage',
            field=models.FloatField(),
        ),
    ]
